apiVersion: v1 
kind: Service 
metadata: 
  name: app-product-svc 
  labels: 
    app: product-service-svc 
spec: 
  selector: 
    app: product-app
  type: NodePort
  ports: 
    - port: 3000 
      targetPort: 3000 
      nodePort: 32011
  