name: CI/CD for product-service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test
        continue-on-error: true
        
      - name: Build Docker image
        id: docker_build
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t yousef2005/product-service:${IMAGE_TAG} .
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Save IMAGE_TAG
        run: echo "${GITHUB_SHA}" > image_tag.txt

      - name: Upload IMAGE_TAG as artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: image-tag
          path: image_tag.txt

    
      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: docker-image
          path: |
            ./ 

  cd:
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download IMAGE_TAG artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: image-tag

      - name: Set IMAGE_TAG env
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image built in CI
        run: |
          docker pull yousef2005/product-service:${{ env.IMAGE_TAG }}

      - name: Tag Docker image
        run: |
          docker tag yousef2005/product-service:${{ env.IMAGE_TAG }} yousef2005/product-service:latest
          docker tag yousef2005/product-service:${{ env.IMAGE_TAG }} yousef2005/product-service:1.0.${{ github.run_number }}

      - name: Push Docker image
        run: |
          docker push yousef2005/product-service:${{ env.IMAGE_TAG }}
          docker push yousef2005/product-service:latest
          docker push yousef2005/product-service:1.0.${{ github.run_number }}
