name: CI for product-service 
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: 

jobs:
  cipipline: 
    runs-on: ubuntu-latest 
    steps:
      - name: CheckOut 
        uses: actions/checkout@v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@v4  
        with:
          node_version: '18'
      - name: install using npm 
        run: npm install 
      - name: Login to docker hub
        uses: docker/login-action@3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push the image 
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true 
          tags: |
            yousef2005/product-service:latest
            yousef2005/product-service:${{ github.sha }}
            yousef2005/product-service:1.0.${{ github.run_number }}
